# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationClass',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_fi', models.CharField(max_length=255, null=True)),
                ('name_sv', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='classification',
            field=models.ForeignKey(help_text='An organization category, e.g. committee', on_delete=django.db.models.deletion.CASCADE, to='decisions.OrganizationClass'),
        ),
    ]
