# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationClass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time at which the resource was created')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='The time at which the resource was updated')),
                ('origin_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_fi', models.CharField(max_length=255, null=True)),
                ('name_sv', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='decisions.DataSource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='organization',
            name='classification',
            field=models.ForeignKey(help_text='An organization category, e.g. committee', on_delete=django.db.models.deletion.CASCADE, to='decisions.OrganizationClass'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationclass',
            unique_together=set([('data_source', 'origin_id')]),
        ),
    ]
