# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0006_make_created_and_modified_timestamps_modifiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationclass',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The time at which the resource was created'),
        ),
        migrations.AddField(
            model_name='organizationclass',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='decisions.DataSource'),
        ),
        migrations.AddField(
            model_name='organizationclass',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The time at which the resource was updated'),
        ),
        migrations.AddField(
            model_name='organizationclass',
            name='origin_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='organizationclass',
            unique_together=set([('data_source', 'origin_id')]),
        ),
    ]
