# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0007_make_organization_class_datamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='An abbreviation for the organization', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.CharField(db_index=True, default='', help_text='Slug for the organization', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='dissolution_date',
            field=models.DateField(blank=True, db_index=True, help_text='A date of dissolution', null=True),
        ),
    ]
