# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0009_add_post_classification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ('action', 'number')},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='organizationclass',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='postclass',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='organizationclass',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='postclass',
            unique_together=set([]),
        ),
    ]
