# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0010_add_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post',
            field=models.ForeignKey(blank=True, help_text='The post responsible for the event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='decisions.Post'),
        ),
    ]
